package com.myspartansoftware.login.domain.enums;

public enum BillingRecordType {
	ABSENT, FULL_DAY, HALF_DAY, EARLY_RELEASE, DAILY_RATE, WEEKLY_RATE, 
	TWO_TO_THREE_DAYS, FOUR_TO_FIVE_DAYS, FOUR_TO_FIVE_DAYS_BEFORE_AND_AFTER, MORNING,
	TWO_TO_THREE_DAYS_BEFORE_AND_AFTER, TWO_DAY, THREE_DAY, FOUR_DAY, FIVE_DAY
	
}
